### ISSUE TITLE
Failed collecting trace: IndexError index out of range

### ISSUE THREAD

**Issue by MaicoTimmerman** [Instagram/MonkeyType#120]
```
[2018-10-19 10:51:08,987]   ERROR [monkeytype.tracing]: Failed collecting trace
Traceback (most recent call last):
  File "/home/maico/IdeaProjects/viaduct/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 258, in __call__
    self.handle_return(frame, arg)
  File "/home/maico/IdeaProjects/viaduct/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 234, in handle_return
    last_opcode = frame.f_code.co_code[frame.f_lasti]
IndexError: index out of range
[2018-10-19 10:51:08,987]   ERROR [monkeytype.tracing]: Failed collecting trace
Traceback (most recent call last):
  File "/home/maico/IdeaProjects/viaduct/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 258, in __call__
    self.handle_return(frame, arg)
  File "/home/maico/IdeaProjects/viaduct/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 234, in handle_return
    last_opcode = frame.f_code.co_code[frame.f_lasti]
IndexError: index out of range
...
additional 40 same traces
...
[2018-10-19 10:51:08,988]   ERROR [monkeytype.tracing]: Failed collecting trace
Traceback (most recent call last):
  File "/home/maico/IdeaProjects/viaduct/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 258, in __call__
    self.handle_return(frame, arg)
  File "/home/maico/IdeaProjects/viaduct/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 234, in handle_return
    last_opcode = frame.f_code.co_code[frame.f_lasti]
IndexError: index out of range
```
We're running a rather large Flask application, which we recently started adding type hints for. I'd like to use monkeytype. I've attempted to bisect our application, however cannot seem to find the root cause of the error. 

I've tried building a sample to reproduce with a sample application:

```python
from flask import Flask, Blueprint
app = Flask(__name__)

blueprint = Blueprint("hello", __name__)

@blueprint.route("/<int:test>/")
def hello(test: int) -> str:
    return "Hello World!"

app.register_blueprint(blueprint)
app.run(host="0.0.0.0", port=5000, debug=True)
```
However that does not seem to run into the issue. What would be a good approach to find the root cause of the error in monkeytype?

**Comment by mpage** [comment]
@MaicoTimmerman - Thanks for the report! That is a strange error - the index of the last instruction that was executed is outside the bounds of the bytecode in the code object associated with the stack frame. 

I would do the following to gather some extra information:

* Bracket `last_opcode = frame.f_code.co_code[frame.f_lasti]` with a try/catch for `IndexError`
* In the except block, log `frame.f_lasti`, `frame.f_code.co_filename`, and `frame.f_code.co_name`. The first value should tell us whether or not the index is somehow invalid and the latter two will give us the filename and function of the code object.

**Comment by MaicoTimmerman** [comment]
https://gist.github.com/MaicoTimmerman/367930fc099be07e490b301a661b8dd4
I've included the trace, but  it seems that `frame.f_lasti == -1` in all cases.

It seems the issue is related to lxml's code, which has been introduced as requirement to our project by https://github.com/onelogin/python3-saml. From that I've been able to reproduce it using single import:

```python
from onelogin.saml2.auth import OneLogin_Saml2_Auth
```

**Comment by carljm** [comment]
@mpage Maybe this is a case where we should just print a "failed to collect trace" and bail?

**Comment by safijari** [comment]
Running into this same thing in a different context. Any solutions?

**Comment by Niedzwiedzw** [comment]
just stumbled upon the problem. running django tests with pytest

**Comment by li-dennis** [comment]
> @MaicoTimmerman - Thanks for the report! That is a strange error - the index of the last instruction that was executed is outside the bounds of the bytecode in the code object associated with the stack frame.
> 
> I would do the following to gather some extra information:
> 
> * Bracket `last_opcode = frame.f_code.co_code[frame.f_lasti]` with a try/catch for `IndexError`
> * In the except block, log `frame.f_lasti`, `frame.f_code.co_filename`, and `frame.f_code.co_name`. The first value should tell us whether or not the index is somehow invalid and the latter two will give us the filename and function of the code object.
> 
> Edit: In case it wasn't clear, you'll need to modify MonkeyType itself to collect the extra information.

This seems to be an open issue still and I've tried these suggested instructions. The issue seems to stem from an internal package we developed that is cythonized. Is this sufficient to catch as much as the trace as possible for now?

```
        try:
            last_opcode = frame.f_code.co_code[frame.f_lasti]
        except IndexError:
            print(frame.f_lasti)
            print(frame.f_code.co_filename)
            print(frame.f_code.co_name)
```

```
-1
kintervals.pyx
lower
```

**Comment by abdalazizrashid** [comment]
Any update? Same problem
