### ISSUE TITLE
Non-deterministic crash generating stubs: AttributeError: type object ... has no attribute '__args__'

### ISSUE THREAD

**Issue by wcooley** [Instagram/MonkeyType#122]
I am attempting to generate stubs for
mahmoud/boltons@874e930bd6dbd92e64412e1bdb46a4053587c86d and am getting failures that are curiously non-deterministic; I can re-run `monkeytype stub <module>` and eventually it will produce stubs rather than errors.

I am running this on Python 3.6.5, built via `pyenv`, on macOS 10.13.6, through `pytest-monkeytype`:
```
pytest-monkeytype==1.0.1
  - MonkeyType [required: >=18.2.0, installed: 18.8.0]
    - retype [required: Any, installed: 17.12.0]
      - click [required: Any, installed: 6.7]
      - typed-ast [required: Any, installed: 1.1.0]
```

Actually, I had to tweak _pytest-monkeytype_ a bit to get it to work, but as this is happening during stub-generation, after trace-logging is collected, I don't think that could be the cause.

```
Traceback (most recent call last):
 File "/my/venv/bin/monkeytype", line 11, in <module>
    sys.exit(entry_point_main())
  File "/my/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 378, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/my/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 363, in main
    handler(args, stdout, stderr)
  File "/my/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 187, in print_stub_handler
    stub = get_stub(args, stdout, stderr)
  File "/my/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 122, in get_stub
    rewriter=rewriter,
  File "/my/venv/lib/python3.6/site-packages/monkeytype/stubs.py", line 583, in build_module_stubs_from_traces
    defn = get_updated_definition(func, traces, rewriter, ignore_existing_annotations)
  File "/my/venv/lib/python3.6/site-packages/monkeytype/stubs.py", line 256, in get_updated_definition
    return_type = rewriter.rewrite(return_type)
  File "/my/venv/lib/python3.6/site-packages/monkeytype/typing.py", line 236, in rewrite
    typ = rw.rewrite(typ)
  File "/my/venv/lib/python3.6/site-packages/monkeytype/typing.py", line 148, in rewrite
    return rewriter(typ)
  File "/my/venv/lib/python3.6/site-packages/monkeytype/typing.py", line 185, in rewrite_Union
    key_type = key_type or e.__args__[0]
AttributeError: type object 'OrderedMultiDict' has no attribute '__args__'
```

**Comment by carljm** [comment]
Seems like this is happening inside `RewriteConfigDict`. Pretty hard to track down without a consistent repro. Not sure what the source of non-determinism would be. Will leave this open in case anyone else runs into it.

**Comment by michaelmior** [comment]
I'm seeing this consistently when trying to apply changes generated after running tests on the [jsonpath-ng](https://github.com/h2non/jsonpath-ng/) library.

Environment

OS: Ubuntu 20.04
Python: 3.11.3

Steps to reproduce:

1. Clone the repository and install everything in `requirements.txt` and `requirements-dev.txt` in addition to monkeytype.
2. Run `monkeytype run -m pytest -s -v --capture sys --cov jsonpath_ng --cov-report term-missing` to generate type information.
3. Run `monkeytype apply jsonpath_ng.jsonpath` to get the error below.

```
Traceback (most recent call last):
  File "/home/mmior/.local/share/virtualenvs/jsonpath-ng-lzU83DBY/bin/monkeytype", line 8, in <module>
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/stubs.py", line 831, in get_updated_definition
    sys.exit(entry_point_main())
             ^^^^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/cli.py", line 473, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/cli.py", line 458, in main
    handler(args, stdout, stderr)
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/cli.py", line 209, in apply_stub_handler
    stub = get_stub(args, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/cli.py", line 134, in get_stub
    stubs = build_module_stubs_from_traces(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/stubs.py", line 892, in build_module_stubs_from_traces
    defn = get_updated_definition(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/stubs.py", line 831, in get_updated_definition
    arg_types = {name: rewriter.rewrite(typ) for name, typ in arg_types.items()}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/stubs.py", line 831, in <dictcomp>
    arg_types = {name: rewriter.rewrite(typ) for name, typ in arg_types.items()}
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/typing.py", line 483, in rewrite
    typ = rw.rewrite(typ)
          ^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/typing.py", line 352, in rewrite
    return rewriter(typ)
           ^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/typing.py", line 405, in rewrite_Union
    elems = tuple(self.rewrite(e) for e in union.__args__ if not self._is_empty(e))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/typing.py", line 405, in <genexpr>
    elems = tuple(self.rewrite(e) for e in union.__args__ if not self._is_empty(e))
                  ^^^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/typing.py", line 352, in rewrite
    return rewriter(typ)
           ^^^^^^^^^^^^^
  File "/var/data/mmior/virtualenvs/jsonpath-ng-lzU83DBY/lib/python3.11/site-packages/monkeytype/typing.py", line 405, in rewrite_Union
    elems = tuple(self.rewrite(e) for e in union.__args__ if not self._is_empty(e))
                                           ^^^^^^^^^^^^^^
AttributeError: type object 'Union' has no attribute '__args__'
```

**Comment by michaelmior** [comment]
FWIW, I was able to reproduce with Python 3.9 and 3.10 as well.
