### ISSUE TITLE
AttributeError: module 'sys' has no attribute 'real_prefix'

### ISSUE THREAD

**Issue by gvanrossum** [Instagram/MonkeyType#16]
Everything I try to do with the `monkeytype` command-line took gives me this:
```
Traceback (most recent call last):
  File "/Users/guido/v36/bin/monkeytype", line 7, in <module>
    from monkeytype.cli import entry_point_main
  File "/Users/guido/v36/lib/python3.6/site-packages/monkeytype/__init__.py", line 12, in <module>
    from monkeytype.config import (
  File "/Users/guido/v36/lib/python3.6/site-packages/monkeytype/config.py", line 83, in <module>
    venv_real_prefix = getattr(sys, 'real_prefix')
AttributeError: module 'sys' has no attribute 'real_prefix'
```
This is with a venv running Python 3.6.2 on Mac. Maybe you meant `getattr(sys, 'real_prefix', None)` ?

**Comment by carljm** [comment]
Ugh, thanks for the report. Fixed in 9417efe50aacc7b6f714f285832699034a4ef83c and released as 17.12.1.
