### ISSUE TITLE
Monkeytype won't run without compilation

### ISSUE THREAD

**Issue by SimiCode** [Instagram/MonkeyType#194]
I'm trying to run monkeytype completely from the source code, without compiling first. When I renamed `typing.py` to `_typing.py`, I got an unexpected error

 Command: `python3.7 ./monkeytype/__main__.py run example.py`
```
Traceback (most recent call last):
  File "./monkeytype/__main__.py", line 6, in <module>
    from monkeytype.cli import entry_point_main
  File "/usr/local/lib/python3.7/site-packages/MonkeyType-20.4.3.dev1-py3.7.egg/monkeytype/__init__.py", line 11, in <module>
    from monkeytype.config import (
  File "/usr/local/lib/python3.7/site-packages/MonkeyType-20.4.3.dev1-py3.7.egg/monkeytype/config.py", line 20, in <module>
    from monkeytype.db.base import (
  File "/usr/local/lib/python3.7/site-packages/MonkeyType-20.4.3.dev1-py3.7.egg/monkeytype/db/base.py", line 17, in <module>
    from monkeytype.tracing import CallTrace, CallTraceLogger
  File "/usr/local/lib/python3.7/site-packages/MonkeyType-20.4.3.dev1-py3.7.egg/monkeytype/tracing.py", line 35, in <module>
    from monkeytype._typing import get_type
ModuleNotFoundError: No module named 'monkeytype._typing'
```

But when I run `python3.7 -m setup.py install` and re-run that same command, it succeeded.

So, How can I run the library using only source code, without having to compile/install it?

**Comment by carljm** [comment]
Hi Edison! There shouldn't be any need to rename `typing.py` to `_typing.py`. Instead of using `python3.7 ./monkeytype/__main__.py run example.py`, I recommend you try `python3.7 -m monkeytype run example.py`. This will set up `sys.path` correctly and should avoid import problems.
