### ISSUE TITLE
`sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.`

### ISSUE THREAD

**Issue by pkoch** [Instagram/MonkeyType#227]
I get a pretty puzzling error when trying to run `monkeytype run $(which pytest)`:
```
Traceback (most recent call last):
  File "/home/ec2-user/env3/bin/monkeytype", line 8, in <module>
    sys.exit(entry_point_main())
  File "/home/ec2-user/env3/lib/python3.8/site-packages/monkeytype/cli.py", line 396, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/home/ec2-user/env3/lib/python3.8/site-packages/monkeytype/cli.py", line 381, in main
    handler(args, stdout, stderr)
  File "/home/ec2-user/env3/lib/python3.8/site-packages/monkeytype/cli.py", line 224, in run_handler
    runpy.run_path(args.script_path, run_name='__main__')
  File "/home/ec2-user/.pyenv/versions/3.8.1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ec2-user/env3/lib/python3.8/site-packages/monkeytype/tracing.py", line 283, in trace_calls
    logger.flush()
  File "/home/ec2-user/env3/lib/python3.8/site-packages/monkeytype/db/base.py", line 78, in flush
    self.store.add(self.traces)
  File "/home/ec2-user/env3/lib/python3.8/site-packages/monkeytype/db/sqlite.py", line 91, in add
    self.conn.executemany(
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```

What am I doing wrong?

**Comment by carljm** [comment]
Unfortunately I have no idea :/ I haven't seen that error, and don't expect I'll be able to figure it out without a repro. If you do figure it out, and there's something MonkeyType can do to avoid it, would definitely be open to fixing!

**Comment by pkoch** [comment]
This was over using https://github.com/pokidovea/immobilus. Switched to https://github.com/spulec/freezegun, added an exception for monkeytype, and things started working.
