### ISSUE TITLE
failed collecting trace: TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object

### ISSUE THREAD

**Issue by permezel** [Instagram/MonkeyType#244]
First time using this tool, after watching the [utoob](https://www.youtube.com/watch?v=pMgmKJyWKn8) discussion.  No type info whatsoever in my code, but I was prepared to be converted, and was interested to get a leg up with this tool.

`monkeytype run zwi/zwi.py 
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Failed collecting trace
Traceback (most recent call last):
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 259, in __call__
    self.handle_call(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 213, in handle_call
    func = self._get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 207, in _get_func
    self.cache[code] = get_func(frame)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 151, in get_func
    func = get_func_in_mro(first_arg, code)
  File "/Users/dap/Library/Python/3.9/lib/python/site-packages/monkeytype/tracing.py", line 113, in get_func_in_mro
    val = inspect.getattr_static(obj, code.co_name, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1622, in getattr_static
    instance_result = _check_instance(obj, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1572, in _check_instance
    return dict.get(instance_dict, attr, _sentinel)
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object
Usage: python -m zwi [OPTIONS] COMMAND [ARGS]...
`

**Comment by carljm** [comment]
Hi! Thanks for the report. I'm afraid that Python is so dynamic it's impossible to know that we've covered every case in type tracing, and "failed collecting trace" warnings are not uncommon. Often many types have been collected despite a few trace-collection warnings and useful stubs can still be generated.

In order to make any progress on the specific warning, I think a repro case will be necessary. Is the code you are running this on publicly available? Can you provide repeatable steps to reproduce this error? Thanks!

**Comment by permezel** [comment]
One thing obvious here in need of fixing is the massive noise to signal ratio.  It is quite simple to catch exceptions and print meaningful, even helpful, errors.  Please consider make this adjustment.  You do not need any more information to make that fix.  Based on googling for similar issues, I see going back at least to 2017 others who have been similarly perplexed.

**Comment by permezel** [comment]
See https://github.com/permezel/zwi/blob/main/zwi/zwi.py.  The version I ran it against has diverged, but I imagine it would act the same.

**Comment by carljm** [comment]
Filed #245 to improve output of trace collection failure warnings; thanks for the suggestion.

**Comment by ekohilas** [comment]
For me, this seemed to happen when `import matplotlib.pyplot`  was included, giving the following during debugging.

**Comment by technicalgrp89** [comment]
How to reesolve this? Any leads?

**Comment by gitgithan** [comment]
In my `file.py`, just doing `import pandas as pd` get `TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'NoneType' object` on `monkeytype run file.py`.

I'm trying some code to see if monkeytype works on classes from 3rd party libraries like pandas since the README only shows adding 2 int. 

I'm also keeping things as simple as possible by using only 1 file. Not sure why the README shows the function defined in a different file and requiring `from some.module import add`
```
import pandas as pd

df1 = pd.DataFrame([1, 2])
df2 = pd.DataFrame([3, 4])


def concat(df1, df2):
    return pd.concat([df1, df2], axis=0, ignore_index=True)

print(concat(df1, df2))
```

Does monkeytype work for the above?
What does the error in the title of this issue mean and when/why does it happen?
