### ISSUE TITLE
ContextManager

### ISSUE THREAD

**Issue by LodeVanB** [Instagram/MonkeyType#27]
$ monkeytype run
Traceback (most recent call last):
  File "/usr/local/bin/monkeytype", line 7, in <module>
    from monkeytype.cli import entry_point_main
  File "/usr/local/lib/python3.5/dist-packages/monkeytype/__init__.py", line 7, in <module>
    from typing import (
ImportError: cannot import name 'ContextManager'

**Comment by carljm** [comment]
What version of python are you using?

**Comment by carljm** [comment]
Never mind; I see python3.5 in the traceback. MonkeyType requires Python 3.6+.
