### ISSUE TITLE
"Exception: Should not receive a TypedDict type in RenderAnnotation" with mypy_extensions.TypedDict

### ISSUE THREAD

**Issue by gsnedders** [Instagram/MonkeyType#342]
Trying to annotate/create stubs for:

```python
from mypy_extensions import TypedDict


class RunInfo(TypedDict):
    revision: str


class RawWPTReport(TypedDict):
    run_info: RunInfo


def run_info(report: RawWPTReport) -> RunInfo:
    return report["run_info"]


def main():
    revision = "0bdaaf9c1622ca49eb140381af1ece6d8001c934"
    report: RawWPTReport = {
        "run_info": {
            "revision": revision,
        },
    }
    assert run_info(report)["revision"] == revision
```

With a database created by calling `monkeytype run foo_b.py`, where `foo_b.py` is just `import foo; foo.main()`, running `monkeytype stub foo` results in:

```
Traceback (most recent call last):
  File "/tmp/venv/bin/monkeytype", line 8, in <module>
    sys.exit(entry_point_main())
             ^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/cli.py", line 473, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/cli.py", line 458, in main
    handler(args, stdout, stderr)
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/cli.py", line 260, in print_stub_handler
    output = stub.render()
             ^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/stubs.py", line 698, in render
    parts.append(func_stub.render())
                 ^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/stubs.py", line 518, in render
    s += render_signature(self.signature, 120 - len(s), prefix) + ": ..."
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/stubs.py", line 429, in render_signature
    formatted = render_parameter(param)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/stubs.py", line 401, in render_parameter
    rendered = render_annotation(anno)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/stubs.py", line 382, in render_annotation
    return RenderAnnotation().rewrite(anno)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/stubs.py", line 372, in rewrite
    rendered = super().rewrite(typ)
               ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/typing.py", line 352, in rewrite
    return rewriter(typ)
           ^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/typing.py", line 329, in rewrite_TypedDict
    {
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/typing.py", line 330, in <dictcomp>
    name: self.rewrite(typ)
          ^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/stubs.py", line 372, in rewrite
    rendered = super().rewrite(typ)
               ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/typing.py", line 352, in rewrite
    return rewriter(typ)
           ^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/typing.py", line 327, in rewrite_TypedDict
    return self.make_builtin_typed_dict(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.11/site-packages/monkeytype/stubs.py", line 318, in make_builtin_typed_dict
    raise Exception(
Exception: Should not receive a TypedDict type in RenderAnnotation, but was called with name=RunInfo, annotations={'revision': 'str'}, total=True.
```

This is:

```
(venv) gsnedders@gsnedders-milk tmp % python3 --version
Python 3.11.10
(venv) gsnedders@gsnedders-milk tmp % pip freeze
libcst==1.5.0
MonkeyType==23.3.0
mypy-extensions==1.0.0
PyYAML==6.0.2
```

This also happens with MonkeyType installed from git, as of 70c3acf62950be5dfb28743c7a719bfdecebcd84.

This appears to only happen with `mypy_extensions.TypedDict` and not `typing.TypedDict`.

**Comment by lkorbel** [comment]
`my_extensions.TypedDict` is [deprecated](https://github.com/python/mypy_extensions/blob/9fc7fe08c8e638cdd9bbf1aa9bf188aef4fd24ef/mypy_extensions.py#L63).
