### ISSUE TITLE
Can't monkeytype Celery

### ISSUE THREAD

**Issue by jonashaag** [Instagram/MonkeyType#35]
```
git clone https://github.com/celery/celery
cd celery/
python setup.py test # for quick install of test dependencies
monkeytype run setup.py test
```

```
Failed collecting trace
Traceback (most recent call last):
  File "/private/tmp/tmp2/celery/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 252, in __call__
    self.handle_return(frame, arg)
  File "/private/tmp/tmp2/celery/venv/lib/python3.6/site-packages/monkeytype/tracing.py", line 227, in handle_return
    typ = get_type(arg)
  File "/private/tmp/tmp2/celery/venv/lib/python3.6/site-packages/monkeytype/typing.py", line 76, in get_type
    val_type = shrink_types(get_type(v) for v in obj.values())
  File "/private/tmp/tmp2/celery/venv/lib/python3.6/site-packages/monkeytype/typing.py", line 39, in shrink_types
    return Union[types]
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 679, in inner
    return cached(*args, **kwds)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 803, in __getitem__
    return self.__class__(parameters, origin=self, _root=True)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 743, in __new__
    parameters = _remove_dups_flatten(parameters)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 647, in _remove_dups_flatten
    for t2 in all_params - {t1}
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 649, in <genexpr>
    t2.__origin__ is not None)):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 1153, in __subclasscheck__
    return super().__subclasscheck__(cls)
  File "/usr/local/bin/../Cellar/python3/3.6.3/bin/../Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 884, in __extrahook__
    if issubclass(subclass, scls):
  File "/usr/local/bin/../Cellar/python3/3.6.3/bin/../Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/private/tmp/tmp2/celery/.eggs/vine-1.1.4-py3.6.egg/vine/abstract.py", line 33, in __subclasshook__
    if cls is Thenable:
NameError: name 'Thenable' is not defined
```

Not sure if this is a MonkeyType issue, or a typing module one.

**Comment by carljm** [comment]
When I follow your steps, I am able to monkeytype Celery, there is just some error output in some cases where MonkeyType is unable to record a trace for some call. But these errors are just caught and printed, they don't prevent tracing from continuing. I end up with a `monkeytype.sqlite3` containing over 6 million call traces, and I'm able to generate stubs from it (though first I have to actually `pip install` the dependencies, since deps installed by setuptools as local eggs aren't accessible when not running `setup.py test`).

I see a number of different error messages from traces that fail to record, the above traceback is just one of them.

In general, I'm not surprised that in a codebase as large and dynamic as Celery, there are a number of cases where MonkeyType is unable to record a specific trace or generate a specific stub. I'm closing this issue since AFAICS "can't monkeytype Celery" is not true, but I'm open to more specific issues for specific cases of inability to trace or stub.

I'm pretty much stumped by the specific traceback you posted; I can't see why or how `Thenable` would be undefined at that point in the code, or how MonkeyType would cause that.
