### ISSUE TITLE
using `monkeytype run pytest` results in error

### ISSUE THREAD

**Issue by jnoortheen** [Instagram/MonkeyType#43]
I've seen this #25 and tried to invoke `pytest` command as `monkeytype run pytest` but this results in following error

```
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/venv/bin/monkeytype", line 11, in <module>
    sys.exit(entry_point_main())
  File "/home/user/.local/share/virtualenvs/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 257, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/home/user/.local/share/virtualenvs/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 245, in main
    handler(args, stdout, stderr)
  File "/home/user/.local/share/virtualenvs/venv/lib/python3.6/site-packages/monkeytype/cli.py", line 130, in run_handler
    runpy.run_path(args.script_path, run_name='__main__')
  File "/usr/lib64/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/lib64/python3.6/runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pytest'
```

**Comment by jnoortheen** [comment]
running it as 
```
monkeytype run `which pytest` 
```
works. I am closing this issue. Maybe adding this to documentation could help others.

**Comment by tingkai-zhang** [comment]
Hi I was not able to make this work by following @jnoortheen 's approach.

My pytest file `root/tests/test_func_a.py`  looks like this:

```
import pytest
from some_package.some_module import func_a

class TestClassA():
    def test_func_a():
    
```

In `root/` I run:
```
monkeytype run `tests/test_func_a.py`
```
but there is not traces generated in sqllite db.

python: 3.7.4
pytest 5.3.5
monkeytype: 19.11.2



Any help appreciated! @carljm

**Comment by MartinThoma** [comment]
I've just created a `run.py`:

```
import pytest

pytest.main()
```

and executed `monkeytype run run.py`
