### ISSUE TITLE
ERROR:monkeytype.tracing:Failed collecting trace

### ISSUE THREAD

**Issue by liacoponi** [Instagram/MonkeyType#45]
After running monkeytype.exe run on my script (Windows 10, python 3.6.2), I get the error below: 

Notice that the .sql file is dumped, and the error only occurs after my script is executed.

> ERROR:monkeytype.tracing:Failed collecting trace
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\monkeytype\tracing.py", li                                                   ne 252, in __call__
    self.handle_return(frame, arg)
  File "c:\program files\python36\lib\site-packages\monkeytype\tracing.py", li                                                   ne 227, in handle_return
    typ = get_type(arg)
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 76, in get_type
    val_type = shrink_types(get_type(v) for v in obj.values())
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 34, in shrink_types
    types = tuple(types)
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 76, in <genexpr>
    val_type = shrink_types(get_type(v) for v in obj.values())
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 62, in get_type
    return Type[obj]
  File "c:\program files\python36\lib\typing.py", line 652, in inner
    return func(*args, **kwds)
  File "c:\program files\python36\lib\typing.py", line 1098, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "c:\program files\python36\lib\typing.py", line 1098, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "c:\program files\python36\lib\typing.py", line 376, in _type_check
    raise TypeError("Plain %s is not valid as type argument" % arg)
TypeError: Plain typing.Generic is not valid as type argument
ERROR:monkeytype.tracing:Failed collecting trace
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\monkeytype\tracing.py", li                                                   ne 252, in __call__
    self.handle_return(frame, arg)
  File "c:\program files\python36\lib\site-packages\monkeytype\tracing.py", li                                                   ne 227, in handle_return
    typ = get_type(arg)
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 76, in get_type
    val_type = shrink_types(get_type(v) for v in obj.values())
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 34, in shrink_types
    types = tuple(types)
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 76, in <genexpr>
    val_type = shrink_types(get_type(v) for v in obj.values())
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 62, in get_type
    return Type[obj]
  File "c:\program files\python36\lib\typing.py", line 652, in inner
    return func(*args, **kwds)
  File "c:\program files\python36\lib\typing.py", line 1098, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "c:\program files\python36\lib\typing.py", line 1098, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "c:\program files\python36\lib\typing.py", line 376, in _type_check
    raise TypeError("Plain %s is not valid as type argument" % arg)
TypeError: Plain typing.Generic is not valid as type argument
ERROR:monkeytype.tracing:Failed collecting trace
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\monkeytype\tracing.py", li                                                   ne 252, in __call__
    self.handle_return(frame, arg)
  File "c:\program files\python36\lib\site-packages\monkeytype\tracing.py", li                                                   ne 227, in handle_return
    typ = get_type(arg)
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 76, in get_type
    val_type = shrink_types(get_type(v) for v in obj.values())
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 34, in shrink_types
    types = tuple(types)
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 76, in <genexpr>
    val_type = shrink_types(get_type(v) for v in obj.values())
  File "c:\program files\python36\lib\site-packages\monkeytype\typing.py", lin                                                   e 62, in get_type
    return Type[obj]
  File "c:\program files\python36\lib\typing.py", line 652, in inner
    return func(*args, **kwds)
  File "c:\program files\python36\lib\typing.py", line 1098, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "c:\program files\python36\lib\typing.py", line 1098, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "c:\program files\python36\lib\typing.py", line 376, in _type_check
    raise TypeError("Plain %s is not valid as type argument" % arg)
TypeError: Plain typing.Generic is not valid as type argument

**Comment by carljm** [comment]
MonkeyType should work normally even with these errors logged, it's just notifying you that it was unable to collect traces for certain calls. It should still be able to create stubs based on all other traces it collected.

Maybe we need to make the error logging clearer in some way; perhaps omit the traceback unless specifically requested for debugging?

It looks like you might be running MonkeyType on code that passes around a `typing.Generic` instance?

**Comment by liacoponi** [comment]
Yes, it is possible. Maybe issue a warning rather than an error would make more sense in these cases, as you suggested. Thanks.

**Comment by gurunath-p** [comment]
I am getting a similar warning when I use _monkeytype run <my_program>_. The program gets stuck with the following warning repeatedly:

> Failed collecting trace
Traceback (most recent call last):
  File "/home/guru-6939/miniconda3/lib/python3.6/site-packages/monkeytype/tracing.py", line 258, in __call__
    self.handle_return(frame, arg)
  File "/home/miniconda3/lib/python3.6/site-packages/monkeytype/tracing.py", line 234, in handle_return
    last_opcode = frame.f_code.co_code[frame.f_lasti]
IndexError: index out of range

Any way to debug this further? Thanks.

**Comment by mpage** [comment]
@gurunath-p - That looks like a different error. Can you open an issue and, if possible, provide us with a way to reproduce the problem?
