### ISSUE TITLE
retype fails

### ISSUE THREAD

**Issue by domoritz** [Instagram/MonkeyType#48]
Trying with https://github.com/domoritz/draco. 

```
monkeytype run draco/cli.py examples/histogram.json
```

Then `monkeytype apply draco.spec` results in

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/asp/bin/monkeytype", line 11, in <module>
    sys.exit(entry_point_main())
  File "/usr/local/anaconda3/envs/asp/lib/python3.6/site-packages/monkeytype/cli.py", line 257, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/usr/local/anaconda3/envs/asp/lib/python3.6/site-packages/monkeytype/cli.py", line 245, in main
    handler(args, stdout, stderr)
  File "/usr/local/anaconda3/envs/asp/lib/python3.6/site-packages/monkeytype/cli.py", line 113, in apply_stub_handler
    subprocess.run(cmd, shell=True, check=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/local/anaconda3/envs/asp/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'retype --pyi-dir /var/folders/g1/bvh0x71s0tg04jq6py_svvdh0000gp/T/monkeytype97qemy3r --target-dir /Users/domoritz/Developer/UW/draco/draco /Users/domoritz/Developer/UW/draco/draco/spec.py' returned non-zero exit status 1.
```

**Comment by carljm** [comment]
Thanks for the report! Retype has a useful error message here, for some reason it's not getting piped through to monkeytype output like it should. Filed #49 for that issue.

The problem is that the generated stub has `Optional[str]` as the annotation for `url` param of `Data.__init__`, but your source code has just `str` for that annotation. This shouldn't be possible; we are supposed to always privilege the actual annotations in the source over the derived data from tracing. But somehow that's failing in this case.

**Comment by carljm** [comment]
As a workaround, if you change your annotation to `Optional[str]` (probably a good idea anyway, since implicit-optional based on None default is sorta deprecated, the preferred mypy behavior is the `no-implicit-optionals` flag), apply should succeed.

**Comment by domoritz** [comment]
Thank you for the quick response and I'm glad that my issue report was useful.
