### ISSUE TITLE
Type hint uses Optional but it's not imported

### ISSUE THREAD

**Issue by johnarnold** [Instagram/MonkeyType#74]
Occasionally I get an error where Optional[ ] hint is generated, but the "from typing import Optional" is not generated.

Placeholder issue until I can set up a minimal repro (I have a repro in real code).

**Comment by johnarnold** [comment]
```python
Traceback (most recent call last):
  File "/home/johnar/venv/net-task/bin/monkeytype", line 11, in <module>
    load_entry_point('MonkeyType', 'console_scripts', 'monkeytype')()
  File "/home/johnar/github/MonkeyType/monkeytype/cli.py", line 377, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/home/johnar/github/MonkeyType/monkeytype/cli.py", line 362, in main
    handler(args, stdout, stderr)
  File "/home/johnar/github/MonkeyType/monkeytype/cli.py", line 130, in apply_stub_handler
    stub = get_stub(args, stdout, stderr)
  File "/home/johnar/github/MonkeyType/monkeytype/cli.py", line 105, in get_stub
    traces.append(thunk.to_trace())
  File "/home/johnar/github/MonkeyType/monkeytype/encoding.py", line 183, in to_trace
    function = get_func_in_module(self.module, self.qualname)
  File "/home/johnar/github/MonkeyType/monkeytype/util.py", line 38, in get_func_in_module
    func = get_name_in_module(module, qualname)
  File "/home/johnar/github/MonkeyType/monkeytype/util.py", line 75, in get_name_in_module
    obj = importlib.import_module(module)
  File "/home/johnar/venv/net-task/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/johnar/scripts-lib/approved-internal-libraries/lib/python/packages/atom/atom/filters/__init__.py", line 10, in <module>
    def get_jinja_env(package_name: Optional[str] = None) -> Environment:
NameError: name 'Optional' is not defined

**Comment by johnarnold** [comment]
code diff from running `monkeytype apply atom.filters`   What's interesting is that it succeeds, no errors.  I only get an error when I try to `monkeytype apply atom.filters.asn` and the import blows up.
```
@ -2,11 +2,12 @@ from jinja2 import Environment, PackageLoader, exceptions
 import logging
 
 # Setup a logger
+from jinja2.environment import Environment, Template
 logger = logging.getLogger(__name__)
 logger.addHandler(logging.NullHandler())
 
 
-def get_jinja_env(package_name=None):
+def get_jinja_env(package_name: Optional[str] = None) -> Environment:
     """

**Comment by carljm** [comment]
Is this `atom` package publicly available so we can repro on it? If not, can you simplify down to a repro case that you can post here?

Presuming that the code diff above is for the file `atom/filters/__init__.py`, it's not surprising that `monkeytype apply atom.filters.asn` then fails, because it has to import `atom/filters/__init__.py`, which is now missing a needed import. The mystery is just why we don't add the necessary import.

When you `monkeytype stub atom.filters`, is there an import of `Optional` in the stub? If so, the bug is in retype. If not, the bug is in MonkeyType.

**Comment by johnarnold** [comment]
@carljm yep, I came to the same conclusion.  The Optional import is not in the stub:
```
(net-task) johnar@netdev1-westus2:~/scripts-lib/approved-internal-libraries/lib/python/packages/atom/atom/test$ monkeytype stub atom.filters
from jinja2.environment import (
    Environment,
    Template,
)


def get_jinja_env(package_name: Optional[str] = None) -> Environment: ...


def get_jinja_template(jinja_env: Environment, template_name: str) -> Template: ...

```

It's an internal library, so I can't release it. I'll write a repro.

**Comment by carljm** [comment]
Thanks!

**Comment by akx** [comment]
I'm seeing this too.

I don't have a simple repro case, but I have an OSS module this happens with: https://github.com/valohai/django-cavalry/tree/9dc91b2eec073fb1e0a1ac51a74afc41aa62ac5c

```
$ pip install -e .[dev] monkeytype==19.5.0
$ monkeytype run -m pytest
(testing occurs)
$ monkeytype apply cavalry.db
$ git diff
# ...
+from typing import Iterator, Tuple, Union
 class CavalryCursorDebugWrapper(CursorWrapper):
     # This is an enhanced version of `django.db.backends.utils.CursorDebugWrapper`.

-    def execute(self, sql, params=None):
+    def execute(self, sql: str, params: Optional[Union[Tuple[int], Tuple[str, str]]] = None):
         start = get_time()
         try:
```

HTH :)
