### ISSUE TITLE
python 3.7 support

### ISSUE THREAD

**Issue by pawnhearts** [Instagram/MonkeyType#78]
I've updated to python 3.7 beta 2 and get errors with monkeytype

`Python 3.7.0b2 (default, Mar  3 2018, 00:51:31) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import monkeytype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/monkeytype/__init__.py", line 11, in <module>
    from monkeytype.config import (
  File "/usr/local/lib/python3.7/site-packages/monkeytype/config.py", line 20, in <module>
    from monkeytype.db.base import (
  File "/usr/local/lib/python3.7/site-packages/monkeytype/db/base.py", line 17, in <module>
    from monkeytype.tracing import CallTrace, CallTraceLogger
  File "/usr/local/lib/python3.7/site-packages/monkeytype/tracing.py", line 35, in <module>
    from monkeytype.typing import get_type
  File "/usr/local/lib/python3.7/site-packages/monkeytype/typing.py", line 10, in <module>
    from typing import (
ImportError: cannot import name '_Any' from 'typing' (/usr/local/lib/python3.7/typing.py)
`

**Comment by carljm** [comment]
Thanks for the report!

**Comment by Imaclean74** [comment]
is there any workaround for this yet ?

**Comment by carljm** [comment]
Nope. We will soon have a `tox.ini` file (#93), which will make it a lot easier to automate running tests under both 3.6 and 3.7, which is kind of a prereq to having 3.7 support that doesn't regress every time something is changed. Once that lands I plan to land 3.7 fixes and release a new version. Sorry for the delay.

**Comment by carljm** [comment]
18.8.0 is released with this fix.
