### ISSUE TITLE
Running "monkeytype list-modules" without collecting results in Traceback

### ISSUE THREAD

**Issue by pradyunsg** [Instagram/MonkeyType#90]
:bug: on v18.5.1

**Demonstration**

```sh-session
$ ls monkeytype.sqlite3
$ monkeytype list-modules
Traceback (most recent call last):
  File "/[path-to-venv]/bin/monkeytype", line 11, in <module>
    sys.exit(entry_point_main())
  File "/[path-to-venv]/lib/python3.6/site-packages/monkeytype/cli.py", line 376, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/[path-to-venv]/lib/python3.6/site-packages/monkeytype/cli.py", line 361, in main
    handler(args, stdout, stderr)
  File "/[path-to-venv]/lib/python3.6/site-packages/monkeytype/cli.py", line 195, in list_modules_handler
    complain_about_no_traces(args, stderr)
  File "/[path-to-venv]/lib/python3.6/site-packages/monkeytype/cli.py", line 65, in complain_about_no_traces
    module, qualname = args.module_path
AttributeError: 'Namespace' object has no attribute 'module_path'
```

**Comment by carljm** [comment]
Thanks for the report!

**Comment by pradyunsg** [comment]
Is this just a matter of making it print a message and return, instead of calling `complain_about_no_traces`?

**Comment by carljm** [comment]
Yep, looks like it.
